obj-$(CONFIG_TH_SONY_T2) += cxd2834_fe.o

cxd2834_fe-objs = cxd2831_cdx2834_api.o sony_dvb_ascot2d.o sony_ascot2d.o cxd2834frontend.o sony_common.o \
						sony_demod_driver_version.o sony_dvb_demod.o  sony_dvb_demod_monitor.o sony_dvb_demod_monitorC.o \
						sony_dvb_demod_monitorT.o sony_dvb_demodC.o sony_dvb_demodT2.o sony_dvb_demodT.o sony_dvb_integration.o\
						sony_i2c.o sony_math.o sony_stopwatch_port.o  sony_dvb_demod_monitorT2.o

EXTRA_CFLAGS += -Idrivers/media/dvb/dvb-core

