#
# Makefile for the DVB driver.
#

obj-$(CONFIG_AM_DVB) += aml.o

aml-objs=aml_dvb.o aml_dmx.o aml_fe.o

obj-$(CONFIG_AM_MXL101) += mxl101/

obj-$(CONFIG_AM_AVL6211) += avl6211/

obj-$(CONFIG_AM_MN88436) += mn88436/